version: '2'

services:
  pod:
    image: gcr.io/google_containers/pause-amd64:3.0
    ports:
      - '80:80'
    dns:
      - 8.8.8.8

  web:
    image: ${WEB_IMAGE_PATH}:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
    network_mode: 'service:pod'
    env_file:
      - .env-base

  app:
    image: ${APP_IMAGE_PATH}:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: build/php/Dockerfile
      args:
        - BASE_IMAGE_PATH=${APP_BASE_IMAGE_PATH}
        - BASE_IMAGE_VERSION=${APP_BASE_IMAGE_VERSION}
    network_mode: 'service:pod'
    volumes:
      - ./build/utils/dockerize-linux-amd64-v0.6.0:/usr/local/bin/dockerize
      - /tmp
    env_file:
      - .env-base

  db:
    image: postgres:9.6.8-alpine
    environment:
      - TZ=Asia/Novosibirsk
    command: >
      postgres
        -c listen_addresses=*
        -c hba_file=/pg_hba.conf
    volumes:
      - ./build/postgresql/pg_hba.conf:/pg_hba.conf

  cache:
    image: redis:3.2.10-alpine
    ports:
      - '6379'

  dns-cache:
    image: ${DNS_IMAGE_PATH}:${IMAGE_VERSION}
    build:
      context: build/dns-cache
      dockerfile: ./Dockerfile
    ports:
      - "5053:53/udp"