apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  
  name: php-k8s
  
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: php-k8s  
        abtesting: "False"
    spec:
      terminationGracePeriodSeconds: 60  
      nodeSelector: 
        role: worker
      containers: 
      - name: php-k8s-web
        image: "registry.hub.docker.com/igonsk/app-web:master-ad7b6fa177722364f4b16644c6a5d1a07048f8a9"
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        readinessProbe:  
          httpGet:
            path: /healthcheck/readiness
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 75m
            memory: 40M
          limits:
            cpu: 256m
            memory: 80M
      - name: php-k8s-app
        image: "registry.hub.docker.com/igonsk/app-api:master-ad7b6fa177722364f4b16644c6a5d1a07048f8a9"
        volumeMounts:
        - mountPath: /etc/resolv.conf
          name: resolv-conf
          subPath: resolv.conf
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        resources:
          limits:
            cpu: 2048m
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 512Mi
        env:
        - name: YII_DEBUG
          value: "0"
        - name: YII_ENV
          value: prod
        - name: APP_DATABASE
          valueFrom:
            secretKeyRef:
              name: php-k8s-secret
              key: app_db_dsn
        - name: APP_LOG_LEVELS
          value: "error,warning"
        - name: APP_LOG_TARGET
          value: "logstash"
        - name: APP_GELF_HOST
          value: "logstash.local"
        - name: APP_GELF_PORT
          value: "12201"
        - name: APP_GELF_TAGS
          value: "k8s-logs"
        - name: APP_GELF_LOGSTASH_PREFIX
          value: "staging"
        - name: APP_GELF_NAMESPACE
          value: "dream-team"
        - name: APP_REDIS_HOSTNAME
          value: "app-redis.dream-team"
      - name: php-k8s-dns-cache
        image: "registry.hub.docker.com/igonsk/dns-cache:master-ad7b6fa177722364f4b16644c6a5d1a07048f8a9"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        resources:
          requests:
            cpu: 100m
            memory: 32M
          limits:
            cpu: 200m
            memory: 64M
      volumes:
      - name: resolv-conf
        configMap:
          name: php-k8s-resolvconf