apiVersion: v1
kind: Service 
metadata:
  name: php-k8s
  annotations:
    router.deis.io/domains: "php-k8s"  
    router.deis.io/maintenance: "False"  
    router.deis.io/ssl.enforce: "False"  
    router.deis.io/ssl.redirectCode: "307"
    
    prometheus.io/probe: "true" 
    prometheus.io/probe-path: "/healthcheck/external" 
  labels:
    router.deis.io/routable: "true"  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80  
      targetPort: 80  
  selector:
    app: php-k8s 