#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

// comment out the following two lines when deployed to production
getenv('YII_DEBUG') ? define('YII_DEBUG', (bool)getenv('YII_DEBUG')) : define('YII_DEBUG', false);
getenv('YII_ENV') ? define('YII_ENV', (bool)getenv('YII_ENV')) :  define('YII_ENV', 'prod');

require __DIR__ . 'vendor/autoload.php';
require __DIR__ . 'vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . 'config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
